services:
  app:
    image: mcr.microsoft.com/devcontainers/python:3.11
    volumes:
      - .:/workspace
    working_dir: /workspace
    tty: true

  backend:
    image: mcr.microsoft.com/devcontainers/python:3.11
    volumes:
      - .:/workspace
    working_dir: /workspace/backend
    ports:
      - "5001:5001"
    command: bash -c "pip install -r requirements.txt && python run.py"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - PORT=5001

  static:
    image: python:3.11-slim
    volumes:
      - .:/workspace
    working_dir: /workspace
    ports:
      - "8000:8000"
    command: python -m http.server 8000